Algoritmo "atividade1"

Var

n1, n2, soma, subtracao, multiplicacao, divisao : real


Inicio

escreva("Digite o primeiro número: ")
leia (n1)
escreva("Digite o primeiro número: ")
leia (n2)

soma <- n1 + n2
subtracao <- n1 - n2
multiplicacao <- n1 * n2
divisao <- n1 / n2

escreval("Primeiro número: ",  n1)
escreval("Segundo número: ",  n2)
escreval("Soma: ",  soma)
escreval("Subtracao: ",  subtracao)
escreval("Multiplicação: ",  multiplicacao)
escreval("Divisão: ",  divisao)


Fimalgoritmo